// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoliumvlprgssryecypq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbGl1bXZscHJnc3NyeWVjeXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjAxMDEsImV4cCI6MjA1ODIzNjEwMX0.-1n-4wWIVEqpjogx68pn6QsotmzoiE4p39VHuoGFOks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);